# Generated by Django 3.1.6 on 2021-02-18 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('all_points', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_range', models.CharField(max_length=50)),
                ('post_start', models.DecimalField(decimal_places=1, max_digits=4)),
                ('post_end', models.DecimalField(decimal_places=1, max_digits=4)),
                ('cross_roads', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('points', models.JSONField()),
                ('last_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='map.update')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='map.route')),
            ],
        ),
    ]
