# Generated by Django 3.1.6 on 2021-02-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210218_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='post_end',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='post_start',
            field=models.FloatField(null=True),
        ),
    ]
