# Generated by Django 3.1.6 on 2021-03-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20210222_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='next_update',
            field=models.DateTimeField(),
        ),
    ]
